version: 2
updates:
  # Keep frontend dependencies up to date
  - package-ecosystem: "npm"
    directory: "/frontend"
    # Check the npm registry for updates at 2am UTC
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: "build(next): "

    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "pip"
    directory: "/backend/requirements/"
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: "build(python): "

    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"

    commit-message:
      prefix: "build(ci): "

    labels:
      - "dependencies"
      - "CI/CD"

  - package-ecosystem: npm
    directory: "/api"

    schedule:
      interval: daily

    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
      include: scope

    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

    labels:
      - dependencies
      - javascript
