version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/:cached

  backend:
    restart: always
    environment:
      - DJANGO_READ_DOT_ENV_FILE=true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    expose:
      - 3000


  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
        - "5672:5672"

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.celery
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq
      - backend



volumes:
  postgres_data:
    driver: local
