name: API

on:
  push:
    branches:
      - main
    paths-ignore:
      - api/**
  pull_request:
    paths-ignore:
      - api/**

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping job"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping job"

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping job"

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - run: echo "Skipping job"

  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping job"
