name: Django Tests

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the project
        run: docker-compose up
      - name: Run the tests
        run: docker-compose exec backend python manage.py test
